import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
// import 'bootstrap/dist/js/bootstrap.min.js'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // useEffect(() => {
    // if (typeof window !== "undefined") {
    //   require('bootstrap/dist/js/bootstrap.js')
    // }
  // }, [])
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
